# Generated by Django 3.1.1 on 2020-09-01 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, verbose_name='Должность')),
                ('hourly_rate', models.IntegerField(verbose_name='Почасовая ставка')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=70, verbose_name='ФИО')),
                ('phone', models.CharField(max_length=11, verbose_name='Телефон')),
                ('home_address', models.CharField(max_length=70, verbose_name='Адресс')),
                ('characteristic', models.TextField(verbose_name='Характеристика')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='teachers.post')),
            ],
        ),
        migrations.CreateModel(
            name='Thing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_place', models.CharField(max_length=70, verbose_name='Место работы')),
                ('name', models.CharField(max_length=70, verbose_name='Предмет')),
                ('hours', models.IntegerField(verbose_name='Суммарные часы')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.teacher')),
            ],
        ),
    ]
